CREATE TABLE IF NOT EXISTS test (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    year INTEGER NOT NULL,
    origin_id BIGINT NOT NULL REFERENCES origin(id) ON DELETE RESTRICT,
    area_id BIGINT REFERENCES area(id) ON DELETE SET NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);
