CREATE TABLE IF NOT EXISTS question (
    id BIGSERIAL PRIMARY KEY,
    enunciado TEXT NOT NULL,
    identifier VARCHAR(50),
    year INTEGER NOT NULL,
    origin_id BIGINT NOT NULL REFERENCES origin(id) ON DELETE RESTRICT,
    area_id BIGINT NOT NULL REFERENCES area(id) ON DELETE RESTRICT,
    test_id BIGINT REFERENCES test(id) ON DELETE SET NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);
